INSERT INTO PERSON (NAME, last_Name,ADDRESS,CELL_PHONE,CITY_NAME) VALUES ('Andres','Escobar','cra','1244','Envigado');
INSERT INTO PERSON (NAME, last_Name,ADDRESS,CELL_PHONE,CITY_NAME) VALUES ('Camilo','Ruiz','cra','124','Medellin');
INSERT INTO PERSON (NAME, last_Name,ADDRESS,CELL_PHONE,CITY_NAME) VALUES ('Luis','Perez','cra','124','Medellin');
INSERT INTO PERSON (NAME, last_Name,ADDRESS,CELL_PHONE,CITY_NAME) VALUES ('Edward','Villamil','cra','320','Zipaquira');

INSERT INTO POSITION (NAME) VALUES ('DEV');
INSERT INTO POSITION (NAME) VALUES ('QA');
INSERT INTO POSITION (NAME) VALUES ('LEADER');

INSERT INTO EMPLOYEE (SALARY, PERSON_ID, POSITION_ID) VALUES (5000000,1,1);
INSERT INTO EMPLOYEE (SALARY, PERSON_ID, POSITION_ID) VALUES (5000000,2,1);
INSERT INTO EMPLOYEE (SALARY, PERSON_ID, POSITION_ID) VALUES (5000000,3,2);
INSERT INTO EMPLOYEE (SALARY, PERSON_ID, POSITION_ID) VALUES (5000000,4,3);